project:
  type: website
  output-dir: docs

website:
  title: "Caspar David Peter"
  description: "Personal website of Caspar David Peter"
  site-url: https://caspardp.github.io
  repo-url: https://github.com/CasparDP/CasparDP.github.io
  open-graph: true
  twitter-card:
    creator: "@CasparDP"
    site: "@CasparDP"
    description: "This ia description"
    card-style: "summary"
  page-footer: "© 2025, Caspar David Peter"
  navbar:
    title: "Caspar David Peter"
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - papers.qmd
      - teaching.qmd
    page-footer:

format:
  html:
    theme:
      - custom.scss
    mainfont: "Instrument Sans"
    css:
      - academicons.css
    toc: true
    page-layout: full
